import NavBar from '@/components/Navbar/page'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import ThemeProvider from '@/context/Theme'
import SearchProvider from '@/context/SearchBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Rashad's Weather App",
  description: "Weather Forcast Generated by Rashad's Web Development",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Rashad's Tag Pic.jpeg" />
      </head>
      <body className={inter.className}>
          <ThemeProvider>
            <NavBar />
            <SearchProvider>
              {children}
            </SearchProvider>
          </ThemeProvider>
      </body>
    </html>
  )
}
